version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
  worker:
    build: ./backend
    command: celery -A tasks.celery worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
